# Generated by Django 4.0.4 on 2022-05-28 04:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Usuario', '0002_alter_usuario_cpf'),
        ('Veiculo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Agenda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('destino', models.CharField(blank=True, max_length=50, null=True, verbose_name='Destino')),
                ('descricao', models.CharField(blank=True, max_length=50, null=True, verbose_name='Descrição')),
                ('data_saida', models.DateField(blank=True, null=True, verbose_name='Data da Saída')),
                ('data_retorno', models.DateField(blank=True, null=True, verbose_name='Data do Retorno')),
                ('hora_saida', models.TimeField(blank=True, null=True, verbose_name='Hora da Saída')),
                ('hora_retorno', models.TimeField(blank=True, null=True, verbose_name='Hora do Retorno')),
                ('motorista', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='motorista', to='Usuario.motorista', verbose_name='Motorista')),
                ('usuario_cadastro', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='administrador', to='Usuario.administrador', verbose_name='Administrador')),
                ('veiculo', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='veiculo', to='Veiculo.veiculo', verbose_name='Veículo')),
            ],
            options={
                'verbose_name': 'Agenda',
                'verbose_name_plural': 'Agendas',
                'ordering': ['data_saida', 'hora_saida'],
            },
        ),
    ]
