# Generated by Django 4.0.4 on 2022-09-10 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agenda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em:')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modificado em:')),
                ('is_active', models.BooleanField(default=True)),
                ('descricao', models.CharField(blank=True, max_length=250, null=True, verbose_name='Descrição do Agendamento')),
                ('data_saida', models.DateField(blank=True, null=True, verbose_name='Data da Saída')),
                ('data_retorno', models.DateField(blank=True, null=True, verbose_name='Data do Retorno')),
                ('hora_saida', models.TimeField(blank=True, null=True, verbose_name='Hora da Saída')),
                ('hora_retorno', models.TimeField(blank=True, null=True, verbose_name='Hora do Retorno')),
            ],
            options={
                'verbose_name': 'Agenda',
                'verbose_name_plural': 'Agendas',
                'ordering': ['data_saida', 'hora_saida'],
            },
        ),
    ]
