# Generated by Django 4.0.4 on 2022-05-29 21:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Usuario', '0001_initial'),
        ('Agenda', '0001_initial'),
        ('Veiculo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='agenda',
            name='motorista',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='motorista', to='Usuario.motorista', verbose_name='Motorista'),
        ),
        migrations.AddField(
            model_name='agenda',
            name='usuario_cadastro',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='administrador', to='Usuario.administrador', verbose_name='Administrador'),
        ),
        migrations.AddField(
            model_name='agenda',
            name='veiculo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='veiculo', to='Veiculo.veiculo', verbose_name='Veículo'),
        ),
    ]
