# Generated by Django 4.0.4 on 2022-09-06 22:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Usuario', '0001_initial'),
        ('Agenda', '0001_initial'),
        ('Veiculo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='agenda',
            name='motorista',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='motorista_agenda', to='Usuario.motorista', verbose_name='Motorista'),
        ),
        migrations.AddField(
            model_name='agenda',
            name='rotas_veiculos',
            field=models.ManyToManyField(to='Veiculo.rotaveiculo'),
        ),
        migrations.AddField(
            model_name='agenda',
            name='usuario_cadastro',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='usuario_cadastro_agenda', to='Usuario.administrador', verbose_name='Administrador'),
        ),
        migrations.AddField(
            model_name='agenda',
            name='veiculo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='veiculo_agenda', to='Veiculo.veiculo', verbose_name='Veículo'),
        ),
    ]
