# Generated by Django 4.0.4 on 2022-09-29 21:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Agenda', '0001_initial'),
        ('Veiculo', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='agenda',
            name='motorista',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='motorista_agenda', to=settings.AUTH_USER_MODEL, verbose_name='Motorista'),
        ),
        migrations.AddField(
            model_name='agenda',
            name='usuario_cadastro',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='usuario_cadastro_agenda', to=settings.AUTH_USER_MODEL, verbose_name='Usuário do cadastro'),
        ),
        migrations.AddField(
            model_name='agenda',
            name='veiculo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='veiculo_agenda', to='Veiculo.veiculo', verbose_name='Veículo'),
        ),
    ]
