# Generated by Django 4.0.4 on 2022-09-12 22:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Agenda', '0004_alter_agenda_updated_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agenda',
            name='is_active',
        ),
    ]
