# Generated by Django 4.0.4 on 2022-09-10 03:10

import cpf_field.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Usuario', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='cpf',
            field=cpf_field.models.CPFField(blank=True, max_length=14, null=True, unique=True, verbose_name='cpf'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='funcao',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Função'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='habilitacao',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Habilitação'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='matricula',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Matrícula'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='user_type',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Administrativo'), (2, 'Motorista'), (3, 'Porteiro')], default=1),
            preserve_default=False,
        ),
    ]
