# Generated by Django 4.0.4 on 2022-05-28 03:17

import cpf_field.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Usuario', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='cpf',
            field=cpf_field.models.CPFField(blank=True, max_length=14, null=True, unique=True, verbose_name='cpf'),
        ),
    ]
