# Generated by Django 4.0.4 on 2022-09-27 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Usuario', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='user_type',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Administrativo'), (2, 'Motorista'), (3, 'Porteiro')], default=1, verbose_name='Tipo de Usuário'),
            preserve_default=False,
        ),
    ]
