# Generated by Django 4.0.4 on 2022-09-10 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Usuario', '0002_usuario_cpf_usuario_funcao_usuario_habilitacao_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='user_type',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Administrativo'), (2, 'Motorista'), (3, 'Porteiro')], verbose_name='Tipo de Usuário'),
        ),
    ]
