# Generated by Django 4.0.4 on 2022-09-14 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Usuario', '0003_alter_usuario_user_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='user_type',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Administrativo'), (2, 'Motorista'), (3, 'Porteiro')], null=True, verbose_name='Tipo de Usuário'),
        ),
    ]
