# Generated by Django 4.0.4 on 2022-05-29 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Veiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marca', models.CharField(max_length=20, verbose_name='Marca')),
                ('tipo', models.CharField(max_length=20, verbose_name='Tipo')),
                ('placa', models.CharField(max_length=10, unique=True, verbose_name='Placa')),
                ('kilometragem', models.PositiveIntegerField(verbose_name='Kilometragem')),
                ('ano_fabricacao', models.PositiveIntegerField(verbose_name='Ano de Fabricação')),
            ],
            options={
                'verbose_name': 'Veículo',
                'verbose_name_plural': 'Veículos',
                'ordering': ['marca', 'tipo'],
            },
        ),
    ]
