# Generated by Django 4.0.4 on 2022-09-10 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RotaVeiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origem', models.CharField(blank=True, max_length=50, null=True, verbose_name='Origem')),
                ('destino', models.CharField(blank=True, max_length=50, null=True, verbose_name='Destino')),
                ('distancia', models.PositiveIntegerField(verbose_name='Distância')),
                ('descricao', models.CharField(blank=True, max_length=50, null=True, verbose_name='Descrição')),
            ],
            options={
                'verbose_name': 'Rota do Veículo',
                'verbose_name_plural': 'Rotas do Veículo',
                'ordering': ['distancia'],
            },
        ),
        migrations.CreateModel(
            name='Veiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marca', models.CharField(max_length=20, verbose_name='Marca')),
                ('tipo', models.CharField(max_length=20, verbose_name='Modelo')),
                ('placa', models.CharField(max_length=10, unique=True, verbose_name='Placa')),
                ('kilometragem', models.PositiveIntegerField(verbose_name='Kilometragem')),
                ('ano_fabricacao', models.PositiveIntegerField(verbose_name='Ano de Fabricação')),
            ],
            options={
                'verbose_name': 'Veículo',
                'verbose_name_plural': 'Veículos',
                'ordering': ['marca', 'tipo'],
            },
        ),
    ]
