# Generated by Django 4.0.4 on 2022-09-10 14:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Agenda', '0003_remove_agenda_rotas_veiculos'),
        ('Veiculo', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RotaVeiculo',
        ),
    ]
