# Generated by Django 4.0.4 on 2022-09-10 14:44

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Veiculo', '0002_delete_rotaveiculo'),
    ]

    operations = [
        migrations.AddField(
            model_name='veiculo',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Criado em:'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='veiculo',
            name='updated_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Modificado em:'),
            preserve_default=False,
        ),
    ]
