# Generated by Django 4.0.4 on 2022-05-28 20:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Agenda', '0001_initial'),
        ('Usuario', '0002_alter_usuario_cpf'),
    ]

    operations = [
        migrations.CreateModel(
            name='LiberarVeiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('observacoes', models.TextField(blank=True, null=True, verbose_name='Observações')),
                ('assinatura_motorista_saida', models.BooleanField(verbose_name='Assinatura do Porteiro na Saída')),
                ('assinatura_motorista_chegada', models.BooleanField(verbose_name='Assinatura do Porteiro na Chegada')),
                ('km_saida', models.PositiveIntegerField(verbose_name='Kilometragem de Saída')),
                ('km_chegada', models.PositiveIntegerField(verbose_name='Kilometragem de Chegada')),
                ('agendamento', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='agenda_veiculo', to='Agenda.agenda', verbose_name='Agenda')),
                ('porteiro_chegada', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='porteiro_chegada', to='Usuario.porteiro', verbose_name='Porteiro')),
                ('porteiro_saida', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='porteiro_saida', to='Usuario.porteiro', verbose_name='Porteiro')),
                ('responsavel_liberacao', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='administrador_veiculo', to='Usuario.administrador', verbose_name='Administrador')),
            ],
            options={
                'verbose_name': 'Liberar Veículo',
                'verbose_name_plural': 'Liberar Veículos',
                'ordering': ['agendamento', 'responsavel_liberacao'],
            },
        ),
    ]
