# Generated by Django 4.0.4 on 2022-09-29 21:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Agenda', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LiberarVeiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('observacoes', models.TextField(blank=True, null=True, verbose_name='Observações')),
                ('confirmacao_saida', models.BooleanField(null=True, verbose_name='Assinatura do Porteiro na Saída')),
                ('confirmacao_chegada', models.BooleanField(null=True, verbose_name='Assinatura do Porteiro na Chegada')),
                ('km_saida', models.PositiveIntegerField(blank=True, null=True, verbose_name='Kilometragem de Saída')),
                ('km_chegada', models.PositiveIntegerField(blank=True, null=True, verbose_name='Kilometragem de Chegada')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em:')),
                ('updated_at', models.DateTimeField(auto_now_add=True, verbose_name='Modificado em:')),
                ('data_hora_saida', models.DateTimeField(blank=True, null=True, verbose_name='Data e Hora da Saída')),
                ('data_hora_chegada', models.DateTimeField(blank=True, null=True, verbose_name='Data e Hora da Chegada')),
                ('is_active', models.BooleanField(default=True)),
                ('agendamento', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='agendamento_liberacao_veiculo', to='Agenda.agenda', verbose_name='Agenda')),
            ],
            options={
                'verbose_name': 'Liberar Veículo',
                'verbose_name_plural': 'Liberar Veículos',
                'ordering': ['agendamento', 'responsavel_liberacao'],
            },
        ),
    ]
