# Generated by Django 4.0.4 on 2022-09-06 22:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Usuario', '0001_initial'),
        ('LiberarVeiculo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='liberarveiculo',
            name='porteiro_chegada',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='porteiro_chegada_liberacao_veiculo', to='Usuario.porteiro', verbose_name='Porteiro'),
        ),
        migrations.AddField(
            model_name='liberarveiculo',
            name='porteiro_saida',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='porteiro_saida_liberacao_veiculo', to='Usuario.porteiro', verbose_name='Porteiro'),
        ),
        migrations.AddField(
            model_name='liberarveiculo',
            name='responsavel_liberacao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='responsavel_liberacao_veiculo', to='Usuario.administrador', verbose_name='Administrador'),
        ),
    ]
