# Generated by Django 4.0.4 on 2022-05-28 20:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Usuario', '0002_alter_usuario_cpf'),
        ('LiberarVeiculo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='liberarveiculo',
            name='porteiro_chegada',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='porteiro_chegada', to='Usuario.porteiro', verbose_name='Porteiro'),
        ),
        migrations.AlterField(
            model_name='liberarveiculo',
            name='porteiro_saida',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='porteiro_saida', to='Usuario.porteiro', verbose_name='Porteiro'),
        ),
    ]
