# Generated by Django 4.0.4 on 2022-05-29 21:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('LiberarVeiculo', '0001_initial'),
        ('Usuario', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='liberarveiculo',
            name='responsavel_liberacao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='administrador_veiculo', to='Usuario.administrador', verbose_name='Administrador'),
        ),
    ]
