# Generated by Django 4.0.4 on 2022-10-12 21:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('LiberarVeiculo', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='liberarveiculo',
            name='porteiro_saida',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='porteiro_saida_liberacao_veiculo', to=settings.AUTH_USER_MODEL, verbose_name='Porteiro da Saída'),
        ),
    ]
