# Generated by Django 4.0.4 on 2022-05-28 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LiberarVeiculo', '0002_alter_liberarveiculo_porteiro_chegada_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='liberarveiculo',
            name='km_chegada',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Kilometragem de Chegada'),
        ),
        migrations.AlterField(
            model_name='liberarveiculo',
            name='km_saida',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Kilometragem de Saída'),
        ),
    ]
