# Generated by Django 4.0.4 on 2022-10-12 23:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LiberarVeiculo', '0003_alter_liberarveiculo_porteiro_saida'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='liberarveiculo',
            options={'ordering': ['-agendamento'], 'verbose_name': 'Liberar Veículo', 'verbose_name_plural': 'Liberar Veículos'},
        ),
        migrations.RemoveField(
            model_name='liberarveiculo',
            name='is_active',
        ),
    ]
