# Generated by Django 4.0.4 on 2022-09-10 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LiberarVeiculo', '0003_alter_liberarveiculo_porteiro_chegada_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='liberarveiculo',
            name='updated_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Modificado em:'),
        ),
    ]
