# Generated by Django 4.0.4 on 2022-10-26 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LiberarVeiculo', '0004_alter_liberarveiculo_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='liberarveiculo',
            name='confirmacao_chegada',
            field=models.BooleanField(blank=True, null=True, verbose_name='Assinatura do Porteiro na Chegada'),
        ),
        migrations.AlterField(
            model_name='liberarveiculo',
            name='confirmacao_saida',
            field=models.BooleanField(blank=True, null=True, verbose_name='Assinatura do Porteiro na Saída'),
        ),
    ]
