# Generated by Django 4.0.4 on 2022-09-12 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LiberarVeiculo', '0004_alter_liberarveiculo_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='liberarveiculo',
            name='data_hora_chegada',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Data e Hora da Chegada'),
        ),
        migrations.AddField(
            model_name='liberarveiculo',
            name='data_hora_saida',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Data e Hora da Saída'),
        ),
    ]
